### ISSUE TITLE
3.2.5: Released SLP patch in rsync homepage differs from current, and cannot be applied cleanly.

### ISSUE THREAD

**Issue by kraptor** [WayneD/rsync-patches#5]
While updating `rsync` in openSUSE to latest version (3.2.4 -> 3.2.5), I noticed the patch for SLP included in [the official tarball patches](https://download.samba.org/pub/rsync/src/rsync-patches-3.2.5.tar.gz) doesn't apply cleanly to sources released in [the official tarball](https://download.samba.org/pub/rsync/src/rsync-3.2.5.tar.gz).

I switched to use the current one here (a minor annoyance):
https://raw.githubusercontent.com/WayneD/rsync-patches/d899304ea5daa125417f296bdd6f8bff0ed342ca/slp.diff

It would be nice to correct this issue in the next version :)

Cheers, and keep doing such a good job!

**Comment by WayneD** [comment]
Apparently my OS upgrade caused the main configure.sh to ship out created by autoconf 2.69 while all the patches got diffed against a configure.sh created by autoconf 2.71.  Not sure how the release tool managed to do that, but I'll check into it. Only the tar file contains diffs for generated files such as configure.sh (since they try to minimize the need for autoconf when not building from git) so the rest of the file is unchanged compared to the repo version, but using it requires an autoconf run after a git patch.
